### ISSUE TITLE
Can anybody reproduce the results of paper ?

### ISSUE THREAD

**Issue by KelleyYin** [teslacool/SCA#13]
This is outstanding work, using data augmentation in NMT .
I noticed that your experiment is based on [fairseq](https://github.com/pytorch/fairseq).
In your paper, you used big-transformer as the baseline of wmt14-en-de, reported by 28.4 BLEU, but in Fairseq's [paper](https://arxiv.org/pdf/1904.01038.pdf) can reach 29.3 BLEU. 
Is your model different from Facebook?

**Comment by teslacool** [comment]
Yes, we use Fairseq as our codebase.  In addition, the number 28.4 is not our reproduced result, and we directly use it from `attention is all you need`.

we can not get `29.3` bleu score because the result is more related to batchsize. Even if using  `--update-freq`  option to simulate training on 128 gpus,  we can not get this number. I think you can give it a try. In our experiments, we can only set '--max-tokens 2048' due to our additional model size. The baseline we reproduced is 28.6+.
